(module

    ;; =========================================================
    ;; WASM memory
    ;; =========================================================

    (memory (export "memory") 1)


    ;; =========================================================
    ;; Authorized URL SHA-256
    ;;
    ;; 8dd8e91f00ff912072f35f8f8b6d94943d7a376fcfe52b5edffea0d9e63a75d5
    ;; =========================================================

    (data (i32.const 0)
        "\8d\d8\e9\1f\00\ff\91\20"
        "\72\f3\5f\8f\8b\6d\94\94"
        "\3d\7a\37\6f\cf\e5\2b\5e"
        "\df\fe\a0\d9\e6\3a\75\d5"
    )


    ;; =========================================================
    ;; Protected data
    ;;
    ;; Your string:
    ;;
    ;; 5ojBdLJZMUTpfHbat0zjeVHC78io8ogugXZa9L9esyCN3PTUSMYUmfEp6s2
    ;;
    ;; 59 bytes
    ;; =========================================================

    (data (i32.const 64)
        "5ojBdLJZMUTpfHbat0zjeVHC78io8ogugXZa9L9esyCN3PTUSMYUmfEp6s2"
    )


    ;; =========================================================
    ;; check(ptr)
    ;;
    ;; ptr = SHA-256 generated by JavaScript
    ;;
    ;; return:
    ;;   1 = URL authorized
    ;;   0 = URL unauthorized
    ;; =========================================================

    (func (export "check")
        (param $ptr i32)
        (result i32)

        (local $i i32)
        (local $inputByte i32)
        (local $storedByte i32)

        ;; i = 0
        (local.set $i
            (i32.const 0)
        )

        ;; Compare 32 bytes
        (block $done

            (loop $compare

                ;; Finished?
                (br_if $done

                    (i32.ge_u
                        (local.get $i)
                        (i32.const 32)
                    )
                )

                ;; Read supplied hash byte
                (local.set $inputByte

                    (i32.load8_u

                        (i32.add
                            (local.get $ptr)
                            (local.get $i)
                        )
                    )
                )

                ;; Read stored hash byte
                (local.set $storedByte

                    (i32.load8_u
                        (local.get $i)
                    )
                )

                ;; Compare
                (if

                    (i32.ne
                        (local.get $inputByte)
                        (local.get $storedByte)
                    )

                    (then

                        ;; Not authorized
                        (return
                            (i32.const 0)
                        )
                    )
                )

                ;; i++
                (local.set $i

                    (i32.add
                        (local.get $i)
                        (i32.const 1)
                    )
                )

                (br $compare)
            )
        )

        ;; Authorized
        (i32.const 1)
    )


    ;; =========================================================
    ;; get_data_ptr()
    ;;
    ;; Returns the memory location of the protected data.
    ;; =========================================================

    (func (export "get_data_ptr")
        (result i32)

        (i32.const 64)
    )


    ;; =========================================================
    ;; get_data_len()
    ;;
    ;; Returns length of protected data.
    ;; =========================================================

    (func (export "get_data_len")
        (result i32)

        (i32.const 59)
    )

)